version: '3.8'
services:
  tiktok-recorder:
    build:
      context: ./recorder
      dockerfile: Dockerfile
      args:
        COOKIE: ${TIKTOK_COOKIE}
    volumes:
      - ./videos:/app/src/videos
    environment:
      - ROOM_ID=${TIKTOK_ROOM_ID}
      - COOKIE=${TIKTOK_COOKIE}

  uploader:
    entrypoint: ["./upload.sh"]
    build:
      context: ./rclone
      dockerfile: Dockerfile
      args:
        RCLONE_CONFIG_TYPE: s3
        RCLONE_CONFIG_PROVIDER: Linode
        RCLONE_CONFIG_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
        RCLONE_CONFIG_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
        RCLONE_CONFIG_ENDPOINT: ${S3_ENDPOINT}
        RCLONE_CONFIG_ACL: public-read
        BUCKET_NAME: ${S3_BUCKET_NAME}
    volumes:
      - ./videos:/app/videos
    environment:
      - RCLONE_CONFIG_TYPE=s3
      - RCLONE_CONFIG_PROVIDER=${S3_PROVIDER}
      - RCLONE_CONFIG_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - RCLONE_CONFIG_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - RCLONE_CONFIG_ENDPOINT=${S3_ENDPOINT}
      - RCLONE_CONFIG_ACL=${S3_ACL}
      - BUCKET_NAME=${S3_BUCKET_NAME}
    restart: always
    depends_on:
      - tiktok-recorder